apiVersion: apps/v1
#what the yaml file is providing instructions for
kind: Deployment
#information about the file and corresponding app
metadata:
  name: calculator-deployment
  labels:
    app: calculator-app 
#Specifications: how many replicas to run, name of containers, image source and ports
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator-app      
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
      - name: calculator-container
        image: markdevereux/calculator-web-app:3.0
        ports:
        - containerPort: 8080