apiVersion: v1
#What the yaml file is providing instructions for
kind: Pod
#information about the file and corresponding app
metadata:
  name: calculator-pod
  labels:
    run: calculator-pod
    #Specifications: name of containers, image source and ports etc
spec:
  containers:
  - image: markdevereux/calculator-web-app:3.0
    name: calculator-app
    imagePullPolicy: Never
    ports:
    - containerPort: 8080

  

