apiVersion: v1
kind: Pod
metadata:
  name: calculator-pod
  labels:
    run: calculator-pod
spec:
  containers:
  - image: markdevereux/node-web-app:3.0
    name: calculator-app
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: unless-stopped
  

